// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fiap-tech-challenge-producao/internal/adapters/handlers"
	"fiap-tech-challenge-producao/internal/adapters/handlers/http"
	"fiap-tech-challenge-producao/internal/adapters/handlers/pubsub"
	repository2 "fiap-tech-challenge-producao/internal/adapters/repository"
	"fiap-tech-challenge-producao/internal/core/usecase"
	"github.com/rhuandantas/fiap-tech-challenge-commons/pkg/db/mysql"
	"github.com/rhuandantas/fiap-tech-challenge-commons/pkg/messaging"
	"github.com/rhuandantas/fiap-tech-challenge-commons/pkg/middlewares/auth"
	"github.com/rhuandantas/fiap-tech-challenge-commons/pkg/util"
)

// Injectors from wire.go:

func InitializeWebServer() (*handlers.Server, error) {
	healthCheck := http.NewHealthCheck()
	validator := util.NewCustomValidator()
	dbConnector := repository.NewMySQLConnector()
	filaRepo := repository2.NewFilaRepo(dbConnector)
	pegaPedidoPorID := usecase.NewPegaPedidoPorID(filaRepo)
	atualizaStatusProducao := usecase.NewAtualizaStatusProducaoUC(filaRepo)
	cadastrarFila := usecase.NewCadastraFila(filaRepo)
	token := auth.NewJwtToken()
	messagingClient := messaging.NewSqsClient()
	producaoReceiver := pubsub.NewProducaoHandler(cadastrarFila)
	producao := http.NewProducao(validator, pegaPedidoPorID, atualizaStatusProducao, cadastrarFila, token)
	server := handlers.NewAPIServer(healthCheck, producao, producaoReceiver, messagingClient)
	return server, nil
}
