basePath: /
definitions:
  domain.Producao:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      observacao:
        type: string
      pedido_id:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  domain.StatusRequest:
    properties:
      status:
        type: string
    required:
    - status
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a documentation of all endpoints in the API.
  title: Tech Challenge API
  version: 3.0.0
paths:
  /liveness:
    get:
      consumes:
      - '*/*'
      description: get the status of http.
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: Show the status of http.
      tags:
      - Health
  /producao:
    post:
      produces:
      - application/json
      responses: {}
      summary: adiciona pedido a produção
      tags:
      - Producao
  /producao/{oedidoID}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: id do pedido
        in: path
        name: id
        required: true
        type: integer
      - description: status
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/domain.StatusRequest'
      produces:
      - application/json
      responses: {}
      summary: atualiza o status do pedido na producao
      tags:
      - Producao
  /producao/{pedidoID}:
    get:
      parameters:
      - description: id do  pedidos em producao
        in: path
        name: pedidoID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Producao'
      summary: lista pedido em producao
      tags:
      - Producao
  /readiness:
    get:
      consumes:
      - '*/*'
      description: get the status of http.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show the status of http.
      tags:
      - Health
produces:
- application/json
schemes:
- http
securityDefinitions:
  JWT:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
